# Let's start with the basics: this is a PHP project
language: php

# Run on top of a few versions to check compatibility
php:
  - 5.6
  - 7.0
  - nightly

# This triggers builds to run on the new TravisCI infrastructure
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# Install Composer package before testing
install:
  - composer install --no-interaction

script:
  - php vendor/bin/phpunit --coverage-clover build/coverage/xml

after_success:
  - php vendor/bin/codacycoverage clover build/coverage/xml
